Repository vapor/leaf, pull requests merged in 2020-02, with the labels that each got.

#153 Beta 3 Update
  Package.swift
Labels: enhancement, semver-major

#152 Allow Optional values when encoding
  Sources/Leaf/LeafEncoder.swift
Labels: bug, semver-patch

#155 Make app.leaf.cache settable
  Sources/Leaf/LeafProvider.swift
  Tests/LeafTests/LeafTests.swift
Labels: bug, semver-minor
